### ISSUE TITLE
Support for databricks

### ISSUE THREAD

**Issue by vinicius-alves** [baineng/feast-hive#11]
Hello! 

I'm a databricks user looking for a feature store solution, probably feast. May I use this extension to do a better usage of feast on databricks ? 

Congratulations for the extension

Regards,

**Comment by baineng** [comment]
Hi @vinicius-alves ,

How you gonna use it on databricks?

**Comment by vinicius-alves** [comment]
Hi @baineng 

I'm not quite sure yet, I was intending to use the FileSource data source, but I saw your "feast-hive" repository and became wondering if this could help

**Comment by baineng** [comment]
I see, yeah, of course you can use it in the way you want.
