### ISSUE TITLE
Please put fresh version on PyPi

### ISSUE THREAD

**Issue by Felix-neko** [baineng/feast-hive#14]
Hi!

Can you please put 0.16.1 version of feast-hive on PyPi?

**Comment by baineng** [comment]
Hello @Felix-neko, sorry for the late reply, I will have a test and release today.

**Comment by baineng** [comment]
@Felix-neko Just released a new version for feast 0.17.0 with same version number

**Comment by Felix-neko** [comment]
Thank you, bro!
